"""Per-cluster secrets, at ~/.forgelab/<cluster>-credentials.yml.

Deliberately outside the repository: `cluster_registered/` is tracked, so the
cluster's info file carries a pointer to this path and never a password. Same
shape as registry.py — pure render, then write — and standard library only.
"""

from __future__ import annotations

import secrets
from pathlib import Path

from . import paths

# The generated secrets each addon needs. An addon absent from this map (hdfs)
# simply has none.
SECRET_KEYS = {
    "keycloak": ("keycloak_admin_password", "keycloak_app_user_password"),
    "splunk": ("splunk_admin_password",),
}

# token_urlsafe(18) is 24 characters of [A-Za-z0-9_-]: comfortably past Splunk's
# 8-character floor, and safe inside a double-quoted YAML scalar unescaped.
PASSWORD_BYTES = 18


def path(cluster: str) -> Path:
    return paths.FORGELAB_HOME / f"{cluster}-credentials.yml"


def generate(addons) -> dict:
    """A fresh password for every secret the enabled addons need."""
    return {
        key: secrets.token_urlsafe(PASSWORD_BYTES)
        for addon in addons
        for key in SECRET_KEYS.get(addon, ())
    }


def render(cluster: str, values: dict) -> str:
    """Build the credentials file. Pure — every value is passed in."""
    lines = [
        f"# Generated by lab/provisioncluster/scripts/install.py for '{cluster}'.",
        "# Never tracked: cluster_registered/ holds only a pointer to this file.",
    ]
    lines += [f'{key}: "{values[key]}"' for key in sorted(values)]
    return "\n".join(lines) + "\n"


def write(cluster: str, values: dict) -> Path:
    """Write the credentials file, owner-readable only. Returns its path."""
    paths.FORGELAB_HOME.mkdir(parents=True, exist_ok=True)
    creds = path(cluster)
    creds.write_text(render(cluster, values))
    creds.chmod(0o600)
    print(f"==> credentials: {creds}")
    return creds


def ensure(cluster: str, addons) -> dict:
    """The cluster's secrets, minting only the ones not already on disk.

    Regenerating every run would desynchronise this file from any service that
    bakes its password in at first start — Keycloak's admin lives in a database
    that outlives the playbook, so a fresh password locks the lab out of its own
    cluster. Existing values always win; keys belonging to addons that are not
    currently enabled are preserved rather than dropped.
    """
    existing = read(cluster)
    missing = {
        key: secrets.token_urlsafe(PASSWORD_BYTES)
        for addon in addons
        for key in SECRET_KEYS.get(addon, ())
        if key not in existing
    }
    merged = {**existing, **missing}
    if merged:
        write(cluster, merged)
    return merged


def read(cluster: str) -> dict:
    """The cluster's secrets, or {} when the file is absent.

    verify.py needs the passwords to prove a login works; this is how it gets
    them without them ever appearing on a command line.
    """
    creds = path(cluster)
    if not creds.is_file():
        return {}
    values = {}
    for line in creds.read_text().splitlines():
        if line.lstrip().startswith("#") or ":" not in line:
            continue
        key, raw = line.split(":", 1)
        values[key.strip()] = raw.strip().strip('"')
    return values


def remove(cluster: str):
    path(cluster).unlink(missing_ok=True)
