"""The registry of live clusters: cluster_registered/<cluster>_cluster_info.yml.

One tracked file per cluster, written at the end of a successful provision and
removed by deprovision, so the working copy answers "which clusters exist, how
do I ssh in, what is installed" without reading the gitignored inventory.

The YAML is rendered by hand: the host agent has no venv, so this package stays
standard library only.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import NamedTuple

from . import paths

SSH_USER = "ubuntu"

# Values that must not be emitted bare: YAML would load them as something other
# than the string we mean (1.30 -> float, no -> False), or fail to parse.
_RESERVED = {
    "true", "false", "yes", "no", "on", "off", "null", "none", "~", "y", "n",
}
_UNSAFE_CHARS = set(":#{}[]&*!|>'\"%@`,")
_UNSAFE_FIRST = set("-?~&*!|>%@`")

_NODE_FIELDS = ("role", "ip", "cpu", "mem", "disk")


class Node(NamedTuple):
    name: str
    role: str
    ip: str
    cpu: str = ""
    mem: str = ""
    disk: str = ""


def _is_number(text: str) -> bool:
    try:
        float(text)
    except ValueError:
        return False
    return True


def _scalar(value) -> str:
    """Render a value as a YAML scalar, quoting only when bare would change it."""
    text = str(value)
    if (
        not text
        or text != text.strip()
        or text.lower() in _RESERVED
        or _is_number(text)
        or any(char in _UNSAFE_CHARS for char in text)
        or text[0] in _UNSAFE_FIRST
    ):
        escaped = text.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    return text


def _home_relative(path) -> str:
    """~/.forgelab/id_ed25519 rather than a path carrying someone's username."""
    home = str(Path.home())
    text = str(path)
    return f"~{text[len(home):]}" if text.startswith(home) else text


def path(cluster: str) -> Path:
    return paths.REGISTRY_DIR / f"{cluster}_cluster_info.yml"


def nodes_from(hosts, sizing: dict) -> list:
    """Build the node list from inventory [(name, ip)] pairs and tfvars sizing.

    The role comes from the node's own name (`<cluster>-<role>-<n>`, the shape
    the terraform module builds), and keys the `<role>_cpu` / `_mem` / `_disk`
    lookup in the cluster's tfvars.
    """
    nodes = []
    for name, ip in hosts:
        parts = name.split("-")
        role = parts[-2] if len(parts) >= 2 else ""
        nodes.append(
            Node(
                name=name,
                role=role,
                ip=ip,
                cpu=sizing.get(f"{role}_cpu", ""),
                mem=sizing.get(f"{role}_mem", ""),
                disk=sizing.get(f"{role}_disk", ""),
            )
        )
    return nodes


def read_components(report) -> list:
    """The component list ansible reported, or [] when it wrote nothing.

    A thin manifest beats failing a run whose cluster is already up and verified.
    """
    report = Path(report)
    if not report.is_file():
        return []
    try:
        components = json.loads(report.read_text() or "[]")
    except ValueError:
        return []
    return components if isinstance(components, list) else []


def render(cluster: str, cluster_type: str, provisioned_at: str, nodes, components) -> str:
    """Build the cluster's info file. Pure — every value is passed in."""
    example = f"ssh {nodes[0].name}" if nodes else f"ssh {cluster}-mgmt-1"
    lines = [
        "# Generated by lab/provisioncluster/scripts/provision.py. Do not edit.",
        "# Rewritten on every provision; removed on deprovision.",
        f"cluster: {_scalar(cluster)}",
        f"type: {_scalar(cluster_type)}",
        f"provisioned_at: {_scalar(provisioned_at)}",
        "ssh:",
        f"  user: {_scalar(SSH_USER)}",
        f"  key: {_scalar(_home_relative(paths.SSH_KEY))}",
        f"  example: {_scalar(example)}",
    ]

    lines.append("nodes:" if nodes else "nodes: []")
    for node in nodes:
        lines.append(f"  - name: {_scalar(node.name)}")
        lines += [
            f"    {field}: {_scalar(getattr(node, field))}"
            for field in _NODE_FIELDS
            if str(getattr(node, field))
        ]

    lines.append("components:" if components else "components: []")
    for component in components:
        # `name` first, then whatever else the role reported — a role can add
        # fields without this renderer knowing about them.
        lines.append(f"  - name: {_scalar(component.get('name', ''))}")
        lines += [
            f"    {key}: {_scalar(component[key])}"
            for key in sorted(component)
            if key != "name" and str(component[key])
        ]

    return "\n".join(lines) + "\n"


def write(cluster: str, cluster_type: str, provisioned_at: str, nodes, components) -> Path:
    """Write the cluster's info file. Returns its path."""
    paths.REGISTRY_DIR.mkdir(parents=True, exist_ok=True)
    info = path(cluster)
    info.write_text(render(cluster, cluster_type, provisioned_at, nodes, components))
    print(f"==> cluster info: {info}")
    return info


def remove(cluster: str):
    path(cluster).unlink(missing_ok=True)
