"""Per-cluster ssh client config, so `ssh <node-name>` and `ssh <ip>` just work
with the lab key instead of Permission denied (publickey)."""

from __future__ import annotations

from pathlib import Path

from . import paths
from .clusterconfig import CONTROL_ROLE

INCLUDE_LINE = "Include ~/.forgelab/ssh_config.d/*.conf"
_INCLUDE_MARKER = "forgelab/ssh_config.d"


def render(cluster: str, hosts, key=None) -> str:
    """Build the cluster's ssh config from [(name, ip)] pairs.

    Host entries are keyed on both the node name and its IP, so
    `ssh lab1-management-1` and `ssh 192.168.252.34` both land as ubuntu with
    the lab key.

    Host key checking is off on purpose: these VMs are disposable and multipass
    recycles IPs between clusters, so a pinned key is guaranteed to go stale and
    block logins.
    """
    key = paths.SSH_KEY if key is None else key
    out = [
        f"# Generated by lab/provisioncluster/scripts/provision.py "
        f"for cluster '{cluster}'.\n",
        "# Regenerated on every provision; removed on deprovision. Do not edit.\n",
    ]
    for name, ip in hosts:
        out.append(
            f"Host {name} {ip}\n"
            f"  HostName {ip}\n"
            f"  User ubuntu\n"
            f"  IdentityFile {key}\n"
            f"  IdentitiesOnly yes\n"
            f"  StrictHostKeyChecking no\n"
            f"  UserKnownHostsFile /dev/null\n"
            f"  LogLevel ERROR\n\n"
        )
    return "".join(out)


def ensure_include(ssh_config=None):
    """Make sure ~/.ssh/config includes the forge-lab config directory.

    Returns the backup path when an existing config was rewritten, else None.

    The Include must precede any existing `Host *` block: ssh keeps the FIRST
    value it obtains for each option, so a catch-all above us would win.
    """
    ssh_config = Path(ssh_config) if ssh_config else Path.home() / ".ssh" / "config"
    ssh_dir = ssh_config.parent
    ssh_dir.mkdir(parents=True, exist_ok=True)
    ssh_dir.chmod(0o700)

    existing = ssh_config.read_text() if ssh_config.is_file() else ""
    if _INCLUDE_MARKER in existing:
        return None

    backup = None
    if existing:
        backup = Path(f"{ssh_config}.forgelab.bak")
        backup.write_text(existing)
        ssh_config.write_text(f"{INCLUDE_LINE}\n\n{existing}")
    else:
        ssh_config.write_text(f"{INCLUDE_LINE}\n")
    ssh_config.chmod(0o600)
    return backup


def write(cluster: str, hosts) -> Path:
    """Write the cluster's config and wire up the Include. Returns its path."""
    paths.SSH_CONF_DIR.mkdir(parents=True, exist_ok=True)
    conf = paths.SSH_CONF_DIR / f"{cluster}.conf"
    conf.write_text(render(cluster, hosts))
    conf.chmod(0o600)

    backup = ensure_include()
    if backup:
        ssh_config = Path.home() / ".ssh" / "config"
        print(f"==> added forge-lab Include to {ssh_config} (backup: {backup})")
    print(f"==> ssh config: {conf} (try: ssh {cluster}-{CONTROL_ROLE}-1)")
    return conf


def remove(cluster: str):
    (paths.SSH_CONF_DIR / f"{cluster}.conf").unlink(missing_ok=True)
