#!/usr/bin/env bash
# Shared helpers; sourced by every plan's scripts (see ../../README.md).
# Every path is derived from this file's own location, so the scripts work from
# any working directory — Bamboo's build dir, your shell, anywhere.
SHARED_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TF_DIR="$SHARED_DIR/terraform"
# shellcheck disable=SC2034 # consumed by provision.sh after sourcing this file
INV_DIR="$SHARED_DIR/ansible/inventory"

# ansible.cfg is only auto-loaded from the CWD, and these scripts run from the
# caller's directory (Bamboo's build dir, your shell, ...), so point ansible at
# it explicitly. Without this, interpreter_python=auto_silent and friends are
# silently ignored and every play re-emits the interpreter-discovery warning.
export ANSIBLE_CONFIG="$SHARED_DIR/ansible/ansible.cfg"

# Per-cluster ssh client config, so `ssh <node-name>` and `ssh <ip>` just work
# with the lab key instead of Permission denied (publickey).
SSH_KEY="$HOME/.forgelab/id_ed25519"
SSH_CONF_DIR="$HOME/.forgelab/ssh_config.d"

die() { echo "ERROR: $*" >&2; exit 1; }

require_tools() {
  local t
  for t in "$@"; do command -v "$t" >/dev/null || die "missing tool: $t"; done
}

# lab/shared/clusters/<name>.tfvars if present, else defaults.tfvars
resolve_tfvars() {
  local name="$1" f
  f="$SHARED_DIR/clusters/${name}.tfvars"
  [ -f "$f" ] || f="$SHARED_DIR/clusters/defaults.tfvars"
  [ -f "$f" ] || die "no tfvars found (need lab/shared/clusters/defaults.tfvars)"
  echo "$f"
}

# Retry apply once: multipass provider has transient failures (R4)
#
# -parallelism=1 is load-bearing, not tuning: concurrent `multipass launch`
# calls race in multipassd's MAC allocation and every VM of the batch comes up
# with the SAME MAC, so DHCP hands them all one lease. The symptom is three
# nodes sharing an IP and ansible dying with "No route to host". The provider
# exposes no mac attribute, so serializing the launches is the only lever.
tf_apply_retry() {
  terraform -chdir="$TF_DIR" apply -auto-approve -parallelism=1 "$@" && return 0
  echo "terraform apply failed once — retrying in 10s (multipass flakiness)" >&2
  sleep 10
  terraform -chdir="$TF_DIR" apply -auto-approve -parallelism=1 "$@"
}

# Fail loudly if the backend handed out duplicate/empty IPs (see the MAC race
# above). Without this the bad state only surfaces later as an opaque ansible
# "No route to host" against a node that looks fine in `multipass list`.
assert_unique_ips() {
  local inv="$1" ips dupes
  ips=$(awk '/ansible_host=/ {sub(/.*ansible_host=/, ""); print $1}' "$inv")
  [ -n "$ips" ] || die "inventory $inv has no hosts (multipass reported no IPs)"
  dupes=$(echo "$ips" | sort | uniq -d)
  [ -z "$dupes" ] || die "duplicate node IP(s) [$(echo "$dupes" | tr '\n' ' ')] in $inv \
— multipass assigned the same MAC to several VMs; deprovision and re-run"
}

# Generate ~/.forgelab/ssh_config.d/<cluster>.conf from the inventory and make
# sure ~/.ssh/config includes that directory. Host entries are keyed on both the
# node name and its IP, so `ssh lab1-mgmt-1` and `ssh 192.168.252.34` both land
# as ubuntu with the lab key.
write_ssh_config() {
  local cluster="$1" inv="$2" name ip conf ssh_config
  conf="$SSH_CONF_DIR/${cluster}.conf"
  mkdir -p "$SSH_CONF_DIR"
  {
    echo "# Generated by lab/provisioncluster/scripts/provision.sh for cluster '$cluster'."
    echo "# Regenerated on every provision; removed on deprovision. Do not edit."
    awk '/ansible_host=/ {sub(/ansible_host=/, ""); print $1, $2}' "$inv" |
      while read -r name ip; do
        # Host key checking is off on purpose: these VMs are disposable and
        # multipass recycles IPs between clusters, so a pinned key is guaranteed
        # to go stale and block logins.
        printf 'Host %s %s\n  HostName %s\n  User ubuntu\n  IdentityFile %s\n' \
          "$name" "$ip" "$ip" "$SSH_KEY"
        printf '  IdentitiesOnly yes\n  StrictHostKeyChecking no\n  UserKnownHostsFile /dev/null\n  LogLevel ERROR\n\n'
      done
  } > "$conf"
  chmod 600 "$conf"

  ssh_config="$HOME/.ssh/config"
  mkdir -p "$HOME/.ssh"; chmod 700 "$HOME/.ssh"
  if ! grep -q 'forgelab/ssh_config.d' "$ssh_config" 2>/dev/null; then
    # Include must precede any existing `Host *` block: ssh keeps the FIRST
    # value it obtains for each option, so a catch-all above us would win.
    if [ -s "$ssh_config" ]; then
      cp "$ssh_config" "${ssh_config}.forgelab.bak"
      printf 'Include ~/.forgelab/ssh_config.d/*.conf\n\n%s' "$(cat "$ssh_config")" > "${ssh_config}.tmp"
      mv "${ssh_config}.tmp" "$ssh_config"
      echo "==> added forge-lab Include to $ssh_config (backup: ${ssh_config}.forgelab.bak)"
    else
      printf 'Include ~/.forgelab/ssh_config.d/*.conf\n' > "$ssh_config"
    fi
    chmod 600 "$ssh_config"
  fi
  echo "==> ssh config: $conf (try: ssh ${cluster}-mgmt-1)"
}

remove_ssh_config() { rm -f "$SSH_CONF_DIR/${1}.conf"; }
