---
- name: Restart opensearch
  ansible.builtin.systemd:
    name: opensearch
    state: restarted
    daemon_reload: true

- name: Restart opensearch-dashboards
  ansible.builtin.systemd:
    name: opensearch-dashboards
    state: restarted
    daemon_reload: true
