from pathlib import Path

from forgelab import sshconf

HOSTS = [("lab1-mgmt-1", "192.168.252.10"), ("lab1-compute-1", "192.168.252.11")]


def test_render_keys_each_host_on_both_name_and_ip():
    text = sshconf.render("lab1", HOSTS, key=Path("/k"))
    assert "Host lab1-mgmt-1 192.168.252.10\n" in text
    assert "Host lab1-compute-1 192.168.252.11\n" in text


def test_render_emits_the_full_option_block():
    text = sshconf.render("lab1", [HOSTS[0]], key=Path("/k"))
    assert text.endswith(
        "Host lab1-mgmt-1 192.168.252.10\n"
        "  HostName 192.168.252.10\n"
        "  User ubuntu\n"
        "  IdentityFile /k\n"
        "  IdentitiesOnly yes\n"
        "  StrictHostKeyChecking no\n"
        "  UserKnownHostsFile /dev/null\n"
        "  LogLevel ERROR\n\n"
    )


def test_render_marks_the_file_as_generated():
    text = sshconf.render("lab1", HOSTS, key=Path("/k"))
    assert text.startswith("# Generated by")
    assert "cluster 'lab1'" in text


def test_ensure_include_creates_a_missing_config(tmp_path):
    config = tmp_path / ".ssh" / "config"
    assert sshconf.ensure_include(config) is None
    assert config.read_text() == f"{sshconf.INCLUDE_LINE}\n"
    assert config.stat().st_mode & 0o777 == 0o600
    assert config.parent.stat().st_mode & 0o777 == 0o700


def test_ensure_include_prepends_above_an_existing_host_block(tmp_path):
    config = tmp_path / "config"
    config.write_text("Host *\n  ForwardAgent yes\n")
    backup = sshconf.ensure_include(config)

    text = config.read_text()
    assert text.startswith(f"{sshconf.INCLUDE_LINE}\n\n")
    assert text.index(sshconf.INCLUDE_LINE) < text.index("Host *")
    assert backup.read_text() == "Host *\n  ForwardAgent yes\n"


def test_ensure_include_is_idempotent(tmp_path):
    config = tmp_path / "config"
    config.write_text("Host *\n")
    sshconf.ensure_include(config)
    after_first = config.read_text()

    assert sshconf.ensure_include(config) is None
    assert config.read_text() == after_first
