"""Rendering, scalar quoting and lifecycle of the cluster info file."""

import json
from pathlib import Path

import pytest

from forgelab import registry

SIZING = {
    "cluster_type": "k8s",
    "mgmt_cpu": "2",
    "mgmt_mem": "4G",
    "mgmt_disk": "20G",
    "compute_cpu": "2",
    "compute_mem": "3G",
    "compute_disk": "20G",
}

HOSTS = [("lab1-mgmt-1", "192.168.252.10"), ("lab1-compute-1", "192.168.252.11")]

COMPONENTS = [
    {"name": "kubernetes", "version": "1.30"},
    {"name": "containerd"},
    {"name": "flannel", "version": "latest"},
]


@pytest.fixture
def registry_dir(tmp_path, monkeypatch):
    monkeypatch.setattr(registry.paths, "REGISTRY_DIR", tmp_path / "cluster_registered")
    return tmp_path / "cluster_registered"


def render_lab1(nodes=None, components=None):
    return registry.render(
        "lab1",
        "k8s",
        "2026-08-03T14:22:11Z",
        registry.nodes_from(HOSTS, SIZING) if nodes is None else nodes,
        COMPONENTS if components is None else components,
    )


def test_renders_the_whole_file(monkeypatch):
    monkeypatch.setattr(registry.paths, "SSH_KEY", Path.home() / ".forgelab" / "id_ed25519")
    assert render_lab1() == (
        "# Generated by lab/provisioncluster/scripts/provision.py. Do not edit.\n"
        "# Rewritten on every provision; removed on deprovision.\n"
        "cluster: lab1\n"
        "type: k8s\n"
        'provisioned_at: "2026-08-03T14:22:11Z"\n'
        "ssh:\n"
        "  user: ubuntu\n"
        '  key: "~/.forgelab/id_ed25519"\n'
        "  example: ssh lab1-mgmt-1\n"
        "nodes:\n"
        "  - name: lab1-mgmt-1\n"
        "    role: mgmt\n"
        "    ip: 192.168.252.10\n"
        '    cpu: "2"\n'
        "    mem: 4G\n"
        "    disk: 20G\n"
        "  - name: lab1-compute-1\n"
        "    role: compute\n"
        "    ip: 192.168.252.11\n"
        '    cpu: "2"\n'
        "    mem: 3G\n"
        "    disk: 20G\n"
        "components:\n"
        "  - name: kubernetes\n"
        '    version: "1.30"\n'
        "  - name: containerd\n"
        "  - name: flannel\n"
        "    version: latest\n"
    )


def test_quotes_only_what_bare_yaml_would_change():
    assert registry._scalar("1.30") == '"1.30"'
    assert registry._scalar("2") == '"2"'
    assert registry._scalar("no") == '"no"'
    assert registry._scalar("") == '""'
    assert registry._scalar("ssh lab1-mgmt-1: now") == '"ssh lab1-mgmt-1: now"'
    assert registry._scalar("192.168.252.10") == "192.168.252.10"
    assert registry._scalar("4G") == "4G"
    assert registry._scalar("lab1-mgmt-1") == "lab1-mgmt-1"


def test_the_rendered_file_parses_as_yaml():
    yaml = pytest.importorskip("yaml")
    data = yaml.safe_load(render_lab1())
    assert data["cluster"] == "lab1"
    assert data["provisioned_at"] == "2026-08-03T14:22:11Z"
    assert data["nodes"][1] == {
        "name": "lab1-compute-1",
        "role": "compute",
        "ip": "192.168.252.11",
        "cpu": "2",
        "mem": "3G",
        "disk": "20G",
    }
    assert data["components"][0] == {"name": "kubernetes", "version": "1.30"}
    assert data["components"][1] == {"name": "containerd"}


def test_renders_empty_collections_as_flow_sequences():
    text = registry.render("lab1", "k8s", "2026-08-03T14:22:11Z", [], [])
    assert "nodes: []" in text
    assert "components: []" in text
    assert "example: ssh lab1-mgmt-1" in text


def test_reads_role_and_sizing_for_each_node():
    mgmt, compute = registry.nodes_from(HOSTS, SIZING)
    assert (mgmt.role, mgmt.ip, mgmt.mem) == ("mgmt", "192.168.252.10", "4G")
    assert (compute.role, compute.disk) == ("compute", "20G")


def test_tells_the_namenode_apart_from_the_datanodes():
    """The HDFS roles are readable straight off the name: no separate lookup."""
    sizing = {
        "namenode_cpu": "2", "namenode_mem": "4G", "namenode_disk": "20G",
        "datanode_cpu": "2", "datanode_mem": "4G", "datanode_disk": "40G",
    }
    hosts = [
        ("lab1-namenode-1", "192.168.252.20"),
        ("lab1-datanode-1", "192.168.252.21"),
    ]
    namenode, datanode = registry.nodes_from(hosts, sizing)
    assert (namenode.role, namenode.disk) == ("namenode", "20G")
    assert (datanode.role, datanode.disk) == ("datanode", "40G")


def test_omits_sizing_the_tfvars_does_not_carry():
    text = registry.render(
        "lab1", "k8s", "2026-08-03T14:22:11Z", registry.nodes_from(HOSTS, {}), []
    )
    assert "cpu:" not in text
    assert "role: mgmt" in text


def test_reads_the_component_report(tmp_path):
    report = tmp_path / "components.json"
    report.write_text(json.dumps(COMPONENTS))
    assert registry.read_components(report) == COMPONENTS


def test_treats_a_missing_or_broken_report_as_no_components(tmp_path):
    """A verified cluster must not fail the run over a thin manifest."""
    assert registry.read_components(tmp_path / "absent.json") == []
    broken = tmp_path / "broken.json"
    broken.write_text("{not json")
    assert registry.read_components(broken) == []


def test_writes_the_file_creating_the_directory(registry_dir):
    written = registry.write("lab1", "k8s", "2026-08-03T14:22:11Z", [], [])
    assert written == registry_dir / "lab1_cluster_info.yml"
    assert written.read_text().startswith("# Generated by")


def test_removes_the_file_and_tolerates_its_absence(registry_dir):
    registry.write("lab1", "k8s", "2026-08-03T14:22:11Z", [], [])
    registry.remove("lab1")
    assert not (registry_dir / "lab1_cluster_info.yml").exists()
    registry.remove("lab1")
